support variable to enable ws ping pong for jb transcribe
jambonz/freeswitch-modules pull request #101
Opened 2024-08-17 09:29 UTC by xquanluu

https://github.com/jambonz/freeswitch-modules/issues/94

2024-08-19 07:01 UTC, xquanluu commented
Tested on jambonz.me:

1/ ping was sent every 10 seconds
2/ without pong, ws would be closed after 30 seconds

2024-08-19 11:23 UTC, davehorton requested changes

2024-08-19 11:23 UTC, davehorton commented on mod_jambonz_transcribe/audio_pipe.cpp
> +const bool ping_pong_enabled = switch_true(std::getenv("WS_PING_PONG_ENABLED"));
lets not use switch_true() and therefore remove the dependency on switch.h

2024-08-19 11:23 UTC, davehorton commented on mod_jambonz_transcribe/audio_pipe.cpp
> +    ping_pong_enabled ? static_cast<uint16_t>(10) : static_cast<uint16_t>(UINT16_MAX),
let change the env var from WS_PING_PONG_ENABLED to WS_PING_INTERVAL, and when the variable is not defined or is zero set to UINT16_MAX

2024-08-19 11:23 UTC, davehorton commented on mod_jambonz_transcribe/audio_pipe.cpp
> +    ping_pong_enabled ? static_cast<uint16_t>(30) : static_cast<uint16_t>(UINT16_MAX),
lets have another env var for this WS_NO_PONG_HANGUP_INTERVAL

2024-08-20 07:15 UTC, xquanluu commented on mod_jambonz_transcribe/audio_pipe.cpp
> +    ping_pong_enabled ? static_cast<uint16_t>(10) : static_cast<uint16_t>(UINT16_MAX),
fixed

2024-08-20 07:15 UTC, xquanluu commented on mod_jambonz_transcribe/audio_pipe.cpp
> +    ping_pong_enabled ? static_cast<uint16_t>(30) : static_cast<uint16_t>(UINT16_MAX),
fixed

2024-08-22 09:51 UTC, vdharashive commented
@xquanluu and @davehorton this is working as expected

2024-08-22 11:32 UTC, davehorton approved these changes

2024-08-22 11:33 UTC, merged