feat/106: converting playht speed option to float instead of integer
jambonz/freeswitch-modules pull request #107
Opened 2024-08-22 14:17 UTC by rammohan-y

converting playht speed option to float instead of integer

2024-08-22 14:30 UTC, xquanluu commented on mod_playht_tts/playht_glue.cpp
> +      cJSON_AddNumberToObject(jResult, "speed", atof(p->speed));
could you help to update this:
https://github.com/jambonz/freeswitch-modules/blob/main/mod_dub/tts_vendor_parser.cpp#L381 for md_dub

2024-08-22 14:32 UTC, davehorton requested changes

2024-08-22 14:32 UTC, davehorton commented on mod_playht_tts/playht_glue.cpp
> +      cJSON_AddNumberToObject(jResult, "speed", atof(p->speed));
Its possible the user may provide a string that is neither a float nor an integer.  I would like to discard it in this case.  One way to do it is like so
```
double val = strtod(p->speed, NULL);
if (val != 0.0) {
   cJSON_AddNumberToObject(jResult, "speed", val);
}
```
Can you make that change and test it, and test with a garbage value as well.

2024-08-23 13:34 UTC, davehorton approved these changes

2024-08-23 13:36 UTC, davehorton commented
@rammohan-y you must sign off on **all** commits in this repo before they can be accepted.  Please review [these guidelines](https://github.com/jambonz/freeswitch-modules/blob/main/CONTRIBUTING.md) and if you agree, push a commit with the `-s` flag to indicate signoff.

2024-08-23 13:37 UTC, davehorton requested changes
signoff required

2024-08-23 14:31 UTC, rammohan-y commented
> signoff required

How do i signoff?

2024-08-23 14:38 UTC, rammohan-y commented
> Quote reply

signed

2024-08-23 14:49 UTC, davehorton approved these changes

2024-08-23 14:49 UTC, merged