fix elevenlabs and whisper for multiple codec
jambonz/freeswitch-modules pull request #14
Opened 2024-02-28 02:53 UTC by xquanluu

2024-02-28 08:01 UTC, xquanluu commented
Hi @davehorton 
This PR is for fixing elevelabs and whisper Opus

2024-03-12 13:35 UTC, davehorton requested changes

2024-03-12 13:35 UTC, davehorton commented on mod_elevenlabs_tts/mod_elevenlabs_tts.h
> +  uint32_t samples_rate;
typo, can you make `sample_rate`

2024-03-12 13:52 UTC, davehorton approved these changes

2024-03-12 13:52 UTC, merged