Feat/mod dub tts
jambonz/freeswitch-modules pull request #21
Opened 2024-03-15 02:56 UTC by xquanluu

2024-03-16 13:53 UTC, davehorton commented on mod_dub/audio_downloader.h
> +int start_audio_download(HttpPayload_t* payload, int rate,
we need to talk about this.  I don't see why an audio downloader instance needs to know anything about a dub_track_t.  Its meant to be a lower level module that does not need knowledge of the upper level module

2024-03-16 14:53 UTC, xquanluu commented on mod_dub/audio_downloader.h
> +int start_audio_download(HttpPayload_t* payload, int rate,
currently, I'm using dub_track_t to access command queue for each track, but yes, I agreed with you, I will update the code to use cmdQueue pointer instead a whole dub_track

2024-03-17 01:48 UTC, xquanluu commented on mod_dub/audio_downloader.h
> +int start_audio_download(HttpPayload_t* payload, int rate,
Remove dub_track_t from lower layer

2024-03-17 23:48 UTC, davehorton requested changes
The main thing I would like to see changed is that I would like all queuing logic to be contained withing file_loader and audio_downloader.  There should be no queueing logic at all in dub_glue.cpp.  

So when dub_glue.cpp starts a first play command by calling for example
```js
start_file_load(url, track->sampleRate, loop, gain, mutex, (CircularBuffer_t*) track->circularBuffer);
```
and then the app sends a second play command while the first is still playing again, it should simply again call:

```js
start_file_load(url, track->sampleRate, loop, gain, mutex, (CircularBuffer_t*) track->circularBuffer);
```
without having to worry about whether something is already playing on that track -- it is up to the file_loader (and audio_downloader) to know to queue the second play and start it when the current one is finished.

(Now, this will require that filie_loader/audio_downloader return the same `downloadId_t` value for the second play that it did for the first, if the second command arrived while the first is still playing.  We do not want it to return a new download id as we can not have two different ids for queued plays on the same track since we need to be able to kill  everything playing on the track with the `stop_audio_download(int id)` function).

So the apis should be
```js
int start_audio_download(HttpPayload_t* payload, int rate,
  int loop, int gain, switch_mutex_t* mutex, CircularBuffer_t* buffer);
int start_file_load(const char* path, int rate, int loop, int gain, switch_mutex_t* mutex, CircularBuffer_t* buffer);
```

There should really be minimal or no changes needed from current main branch in the dub_glue.cpp other than the need to support http headers and the logic for doing the TTS.

Also, eliminate `DUB_GENERATOR_TYPE_TTS` since it is not used

2024-03-17 23:49 UTC, davehorton commented on mod_dub/common.h
> +typedef struct HttpPayload {
remove from here and define local to audio_downloader.cpp

2024-03-17 23:49 UTC, davehorton commented on mod_dub/common.h
> +typedef std::queue<HttpPayload_t> HttpPayloadQueue_t;
ditto -- should be defined in audio_downloader.cpp

2024-03-17 23:50 UTC, davehorton commented on mod_dub/mod_dub.h
> +  void* cmd_queue;
remove this -- all queueing logic hidden and local only to the downloaders

2024-03-17 23:52 UTC, davehorton commented on mod_dub/mod_dub.c
> +char* next_token(char** str_ptr, const char* delimiters) {
I want to explore whether we can avoid this by encapsulating the tts args in double quotes when we send to freeswitch

2024-03-17 23:54 UTC, davehorton commented on mod_dub/audio_downloader.cpp
> +  std::queue<HttpPayload_t>* cmd_queue;
not a pointer to a queue, but the queue itself since we want everything with regard to queuing encapsulated here

2024-03-17 23:55 UTC, davehorton commented on mod_dub/audio_downloader.cpp
> +  int* generatorId;
should not be needed

2024-03-17 23:55 UTC, davehorton commented on mod_dub/audio_downloader.cpp
> +  dub_generator_t* generator;
should not be needed

2024-03-17 23:55 UTC, davehorton commented on mod_dub/audio_downloader.cpp
> +    conn->cmd_queue = nullptr;
cleanup / not needed

2024-03-17 23:56 UTC, davehorton commented on mod_dub/audio_downloader.cpp
> -  conn->url = strdup(url);
unclear why you removed this.  We need the url

2024-03-17 23:56 UTC, davehorton commented on mod_dub/audio_downloader.cpp
> +  curl_easy_setopt(easy, CURLOPT_URL, payload->url.c_str());
unclear why url would be inside a payload.  Confusing and doesn't make sense

2024-03-17 23:57 UTC, davehorton commented on mod_dub/audio_downloader.cpp
> +      switch_log_printf(SWITCH_CHANNEL_LOG, SWITCH_LOG_DEBUG, "Running to next command, but it's on local file, terminate myself and start file loader\n");
This should never happen, and this logic should be unnecessary.  If there is a scenario where it can happen, then rework program logic so it is impossible to happen.

2024-03-17 23:58 UTC, davehorton commented on mod_dub/common.h
> +
remove

2024-03-18 00:01 UTC, davehorton commented on mod_dub/file_loader.cpp
> +  stop_file_load(oldId);
what's going on here?  I don't understand why we would **ever** stop a download in progress, other than to silence or remove a track

2024-03-18 00:03 UTC, davehorton commented on mod_dub/tts_vendor_parser.cpp
> +  payload.url = url_stream.str();
again, I don't like the concept of a "url" being inside a "payload" since that does not line up to how HTTP protocol works and is therefore needlessly confusing to the reader

2024-03-18 00:04 UTC, davehorton commented on mod_dub/tts_vendor_parser.cpp
> +switch_status_t elevenlabs_parse_text(std::map<std::string, std::string> params, std::string text,  HttpPayload_t& payload) {
How can we rewrite these functions to totally eliminate this new type `HttpPayload`?  Please use only standard c++ types like std:string and std::queue so we can make these functions more portable and reusable

2024-03-18 08:23 UTC, xquanluu commented on mod_dub/audio_downloader.cpp
> +  curl_easy_setopt(easy, CURLOPT_URL, payload->url.c_str());
I'm thinking that I use wrong english words for this, it should not be payload, it should be **command** which includes url, body(optional), header (optional)

2024-03-18 09:20 UTC, xquanluu commented on mod_dub/file_loader.cpp
> +  stop_file_load(oldId);
This is in the case,

The I want to stop file loader to initiate new worker for new URL

2024-03-18 10:34 UTC, xquanluu commented on mod_dub/audio_downloader.cpp
> -  conn->url = strdup(url);
it's included inside the request_t now

```
typedef struct Request {
  std::string url;
  std::string body;
  std::vector<std::string> headers;
} request_t;
```

2024-03-18 10:36 UTC, xquanluu commented on mod_dub/common.h
> +
fixed

2024-03-18 10:37 UTC, xquanluu commented on mod_dub/tts_vendor_parser.cpp
> +  payload.url = url_stream.str();
I updated the name to request instead of payload to avoid confusion

2024-03-18 11:31 UTC, davehorton commented on mod_dub/audio_downloader.cpp
> +  dub_generator_t* generator;
"When file_loader replaced to audio_downloader" - why would this ever happen?  Can you describe the scenario

2024-03-18 12:20 UTC, xquanluu commented on mod_dub/audio_downloader.cpp
> +  dub_generator_t* generator;
We have a queue: file--> http--> file-->http

File loader after loading audio file to buffer will have to kill himself and bring up audio_downloader.

2024-03-24 00:40 UTC, closed without merging