support streaming audio for mod_audio_fork
jambonz/freeswitch-modules pull request #28
Opened 2024-03-26 09:05 UTC by xquanluu

2024-03-27 11:55 UTC, davehorton requested changes

2024-03-27 11:55 UTC, davehorton commented on mod_audio_fork/audio_pipe.cpp
> +            ap->m_callback(ap->m_uuid.c_str(), ap->m_bugname.c_str(), is_binary ? AudioPipe::BINARY : AudioPipe::MESSAGE, msg.c_str());
this results in a copy of the binary data.  I would the expense of a copy operation here, for binary data.  (For text frames it's fine).  I would rather the insert into the circular buffer points to directly the raw incoming read buffer

2024-03-30 09:20 UTC, xquanluu commented on mod_audio_fork/audio_pipe.cpp
> +            ap->m_callback(ap->m_uuid.c_str(), ap->m_bugname.c_str(), is_binary ? AudioPipe::BINARY : AudioPipe::MESSAGE, msg.c_str());
fixed

2024-03-30 09:20 UTC, xquanluu commented
https://github.com/jambonz/freeswitch-modules/issues/25

2024-03-30 13:24 UTC, davehorton requested changes

2024-03-30 13:24 UTC, davehorton commented on mod_audio_fork/audio_pipe.cpp
>            if (lws_is_final_fragment(wsi)) {
I'm not sure about this.  Why was this changed?  This has to do with text frames, not binary frames.  With text frames we can still have the same issue as before where one message is split between different frames and we need to collect and process *only* when the final frame arrives.

2024-03-30 13:25 UTC, davehorton commented on mod_audio_fork/mod_audio_fork.c
> +#define FORK_API_SYNTAX "<uuid> [start | stop | send_text | pause | resume | graceful-shutdown | stop_play ] [wss-url | path] [mono | mixed | stereo] [8000 | 16000 | 24000 | 32000 | 64000] [bugname]
fix typos "bidrectionalAduo"

2024-03-30 13:28 UTC, davehorton commented on mod_audio_fork/audio_pipe.cpp
> +  m_bidirectional_audio_stream = bidirectional_audio_stream > 0;
I'm curious about this.  Why the check > 0?  why not doesn't this work?
```
m_bidirectional_audio_stream = bidirectional_audio_stream
```
the greater than check might make the reader think there is something more involved going on here.....is there?

2024-03-31 11:33 UTC, xquanluu commented on mod_audio_fork/audio_pipe.cpp
>            if (lws_is_final_fragment(wsi)) {
if (nullptr != ap->m_recv_buf) { 

already checked in 180

I'm reverting the code change for this

2024-03-31 11:33 UTC, xquanluu commented on mod_audio_fork/audio_pipe.cpp
> +  m_bidirectional_audio_stream = bidirectional_audio_stream > 0;
fixed

2024-03-31 11:35 UTC, xquanluu commented on mod_audio_fork/mod_audio_fork.c
> +#define FORK_API_SYNTAX "<uuid> [start | stop | send_text | pause | resume | graceful-shutdown | stop_play ] [wss-url | path] [mono | mixed | stereo] [8000 | 16000 | 24000 | 32000 | 64000] [bugname]
fixed

2024-03-31 13:05 UTC, davehorton approved these changes

2024-03-31 13:05 UTC, merged