elevenlabs to use http 1.1
jambonz/freeswitch-modules pull request #57
Opened 2024-04-28 04:45 UTC by xquanluu

2024-04-28 04:53 UTC, xquanluu commented
Hi @davehorton  Tested on jambonz.me, all requests were made on HTTP1.1, audio is clear to hear, no issue

2024-04-28 13:03 UTC, davehorton requested changes

2024-04-28 13:03 UTC, davehorton commented on mod_deepgram_tts/deepgram_glue.cpp
> +    curl_easy_setopt(easy, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
ok but now please add an env var `DISABLE_HTTP2_FOR_TTS_STREAMING` and use http/2 unless it is set equal to 1, then use http 1.1

2024-04-29 07:41 UTC, xquanluu commented on mod_deepgram_tts/deepgram_glue.cpp
> +    curl_easy_setopt(easy, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
fixed

2024-04-29 11:26 UTC, davehorton approved these changes

2024-04-29 11:51 UTC, davehorton approved these changes

2024-04-29 11:51 UTC, merged