support single azure connection for same channel
jambonz/freeswitch-modules pull request #73
Opened 2024-05-31 10:34 UTC by xquanluu

2024-05-31 10:51 UTC, davehorton commented on mod_azure_transcribe/azure_transcribe_glue.cpp
> +			if (++cb->frame_count * 20 /*ms*/ / 1000 >= AZURE_KEEP_ALIVE_INTERVAL_SECOND) {
tell me more about what we are doing here?

2024-05-31 10:51 UTC, davehorton requested changes
this whole feature needs to be enabled by an env var in freeswitch, same as Deepgram

2024-05-31 10:55 UTC, xquanluu commented on mod_azure_transcribe/azure_transcribe_glue.cpp
> +			if (++cb->frame_count * 20 /*ms*/ / 1000 >= AZURE_KEEP_ALIVE_INTERVAL_SECOND) {
I want to keep printing the log for testing and later we can debug that the bug is still alive and azure session is still alive.

2024-06-01 06:02 UTC, xquanluu commented
There is env variable to enable this feature: AZURE_SPEECH_USE_SINGLE_CONNECTION

I have tested this on jambonz.me and thing is working as my expected, long duration transcribe is working, disable gather for 5 mins and re-gather still working.

2024-06-01 06:03 UTC, xquanluu commented on mod_azure_transcribe/azure_transcribe_glue.cpp
> +			if (++cb->frame_count * 20 /*ms*/ / 1000 >= AZURE_KEEP_ALIVE_INTERVAL_SECOND) {
After successfully debug, I removed this code.

2024-06-01 10:59 UTC, davehorton approved these changes

2024-06-01 10:59 UTC, merged